name: Docker-in-Docker with Workspace Volume

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    container:
      image: docker:latest
      options: --privileged

    steps:
      - name: Start Docker Daemon
        run: |
          dockerd-entrypoint.sh &
          sleep 10

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create workspace volume
        run: |
          docker volume create workspace_vol
          docker run --rm \
            -v workspace_vol:/workspace \
            -v ${{ github.workspace }}:/tmp/workspace_src \
            alpine cp -a /tmp/workspace_src/. /workspace/

      # Simple approach: Pull previous image for layer caching
      - name: Pull previous image for caching
        run: |
          docker pull my-custom-image:latest || true

      - name: Build Docker Image with simple caching
        run: |
          docker build \
            --cache-from my-custom-image:latest \
            -t my-custom-image:latest \
            -t my-custom-image \
            -f docker/Dockerfile.test \
            .
          
      - name: Run Container using workspace volume
        run: |
          docker run --rm \
            -v workspace_vol:/app \
            my-custom-image sh -c "echo 'Inside container'; pytest -v tests/test_postgres.py"