name: Docker-in-Docker with Workspace Volume

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    container:
      image: docker:latest
      options: --privileged

    steps:
      - name: Start Docker Daemon
        run: |
          dockerd-entrypoint.sh &
          sleep 10

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create workspace volume
        run: |
          docker volume create workspace_vol
          docker run --rm \
            -v workspace_vol:/workspace \
            -v ${{ github.workspace }}:/tmp/workspace_src \
            alpine cp -a /tmp/workspace_src/. /workspace/

      - name: Build Docker Image using workspace volume
        run: |
          ls docker
          ls ${{ github.workspace }}
          docker build -t my-custom-image docker/Dockerfile.test
          
      - name: Run Container using workspace volume
        run: |
          docker run --rm \
            -v workspace_vol:/app \
            my-custom-image sh -c "echo 'Inside container'; ls -la /app"
