name: Docker Build and Test with DockerHub Caching

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          use: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push with GHCR cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.test
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  run-tests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}

      - name: Run tests in container
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }} \
            sh -c "pytest -v tests/test_postgres.py"
